### PR TITLE
Cleanup setup.cfg

### PR DESCRIPTION
**Pull request by gforcada**
Almost everything goes to `pyproject.toml`, and we get a new file `.flake8`, which hopefully at some point upstream decides to bite the bullet and use `pyproject.toml` as well 😅

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Can't we say that we do not touch `setup.cfg` at all anymore with `plone/meta`?  If any package still needs something in there, they can just have their own version of `setup.cfg`, without needing to put anything in `.meta.toml` for it.

For example the `Plone` package has a lot of `setup.cfg` options that were formerly in `setup.py`, and I don't think we should need to copy those to `.meta.toml`.

Some warnings/checks for `.meta.toml` options that should not be used anymore, would be good though, like you do.

**Review by ericof — APPROVED** [review]
LGTM

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees How many Plone packages do we have with an empty setup.py (with everything on setup.cfg)? I do remember `Plone`, any other?

Let me check in my clone of Plone coredev 6.0 in src:

```
$ wc -l */setup.py | sort -g
       3 Plone/setup.py
       4 plone.base/setup.py
      43 plone.app.mosaic/setup.py
      43 plone.contentrules/setup.py
...
```

So this is only `Plone` and `plone.base`, assuming that there are no such packages lurking that I have not checked out.

**Comment by gforcada** [comment]
That's a really good idea, stop touching setup.cfg and warn if it's still there 👍🏾 

I will try to work on that these next days 😄

**Comment by gforcada** [comment]
Done ✔️ what about like this? 😄

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
